# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "criH8I9WTv7l6gpHbTdfNDpJpst8clcC4CdqI/N2wP5YYjlKdHB/EhmlrTDQKio96f+7d3z0ud4S7VTJENFXx4yalLabWlYuA4/EtN/fSu2rZvt1Z8R0CxbGVEs8zIaW94FwprfKv2vXF1Sc5+GsLg+Sgy2ar2fou2xbZK7ZAS6s9Cs6l52s9mBzl/UWV/l3ec7VfOoCWyTparJFFBNNtFoRc2aroN5jwjgbMuExP5ytOToQedgairZLXZ6BDa/xccoXOivJ5dkIkiP2bSZhQ6mP72itB5qW1AttTrXU3t5bEwpXPLB2+g0DFFdITmAIVvOn3KYm6INX37as8fI5sUToXjRoPczDj8nMbeOTZ5ENo9a4+tTHiqm49ySlHMFdF9A6Y+/Nb03e6mYk+8tt3FoWs7t8xqnPkW+/9EsJk55nsm25av2ZVkVlLwzRITChFGn6Py07RuafmkQWNIN9wozoNFYiBkhC2sHoIJbpPBIukPw95rDrpQ+joNfIk2sSuSpMqNnWBz4z7MFaxmszKtC9LedLD6b8mM43ZQw5JYrqfZ/Mk4Hy0UfcyEtX6Z/XQUPDT972EKdBzd6CHmN9sYFYdyXnM3kRtm0OenhHvZBk77IJ2seDSk+7asXjLm7CrfqqNvUeEjGGlrHLo3f8wnWPHBOikOJq3rxtgDUKmq4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
